from core.BaseEstimator import BaseEstimator
import numpy as np

class LinearDiscriminantAnalysis(BaseEstimator):

  '''
  Linear Discriminant Analysis (LDA)

  sklearn: A classifer with linear decision boundary, generated by fitting class conditional densities to the data and using Bayes' rule.
  '''
  def __init__(self, algorithm_name, algorithm_type, algorithm_params, priors=None):
    super().__init__(algorithm_name, algorithm_type, algorithm_params)
    self.priors = priors
    self.algorithm_params['priors'] = priors
  
  def fit(self, X, y):
    pass 

  def predict(self, X):
    pass 

  def evaluate(self, X, y, metric):
    pass

  

